#!/usr/bin/env python3

def solve(k):
    global v
    
    if k == 0:
        return 0
    elif k == 1:
        return v[0]
    else:
        return max(solve(k - 1), solve(k - 2) + v[k - 1])

if __name__ == "__main__":
    v = [3, 1, 4, 1, 5, 9, 2, 6]
    print(f"Beer drunk: {solve(len(v))}")
