#!/usr/bin/env python3

def solve():
    global v

    (a, b) = (0, v[0])
    for k in range(2, len(v) + 1):
        (a, b) = (b, max(b, a + v[k - 1]))
    return b

if __name__ == "__main__":
    v = [3, 1, 4, 1, 5, 9, 2, 6]
    print(f"Beer drunk: {solve()}")
