#!/usr/bin/env python3

def solve():
    global v

    M = [0, v[0]]
    for k in range(2, len(v) + 1):
        M.append(max(M[k - 1], M[k - 2] + v[k - 1]))
    return M[len(v)]

if __name__ == "__main__":
    v = [3, 1, 4, 1, 5, 9, 2, 6]
    print(f"Beer drunk: {solve()}")
