#!/usr/bin/env python3

fib = {0: 0, 1: 1} # Prefill values

def fibonacci(n):
    if(not n in fib):
        fib[n] = fibonacci(n - 1) + fibonacci(n - 2)
    return fib[n]


if __name__ == "__main__":
    print(f"F(20) = {fibonacci(20)}")
