#!/usr/bin/env python3

def fibonacci(n):
    if n <= 1:
        return n
    (a, b) = (0, 1)
    for i in range(2, n):
        (a, b) = (b, a + b)
    return a + b

if __name__ == "__main__":
    print(f"F(20) = {fibonacci(20)}")
