#!/usr/bin/perl

$n = shift;
$fn = shift;

open(f, ">", $fn);

print f $n, "\n";
for($i = 0; $i < $n; $i++) {
	printf f "%.3f%s", (rand(200) - 100),
	  $i == $n - 1 || ($i + 1) % 10 == 0 ? "\n" : " ";
}
