#!/usr/bin/env python3

from math import atan

def trapezoid(f, a, b, n):
    h = (b - a) / n
    s = (f(a) + f(b)) / 2 + sum([f(a + k * h) for k in range(1, n)])
    return s * h

# Runge function

def runge(x):
    return 1 / (1 + 25 * x ** 2)

N = 9

exact = 2 * atan(5) / 5

E = [exact - trapezoid(runge, -1, 1, 2 ** (k + 1)) for k in range(N)]
C = [E[k] / (2 / 2 **  (k + 1)) ** 2 for k in range(N)]

print("  \\begin{tabular}{>{\\(}c<{\\)}*{2}{D{.}{,}{6}}}")
print("    \multicolumn{1}{c}{\\boldmath\\(h\\)\\unboldmath} &")
print("      \multicolumn{1}{c}{\\textbf{Error}} &")
print("      \multicolumn{1}{c}{\\boldmath\\(C\\)\\unboldmath} \\\\")
print("    \hline")
for k in range(N):
    print("    2 / 2^{0:1d} & {1:11.4e} & {2:11.4e}"
            .format(k + 1, E[k], C[k]),
          end = " \\\\\n" if k < N - 1 else "\n")
print("  \end{tabular}")
