#!/usr/bin/python3

from numpy.polynomial import Polynomial

p = Polynomial([1])

for i in range(1,11):
	p *= [-i, 1]
p += [0 for i in range(5)] + [1] # x**5

print(list(map(int, p.coef)))

print(p.roots())

# LaTeX...

print()

# First term

if p.coef[-1:] != 1:
	print('{:} '.format(int(p.coef[-1:])), end = '')
if len(p.coef) > 10:
	print('x^{{{:}}}'.format(len(p.coef) - 1), end = '')
else:
	print('x^{:}'.format(len(p.coef) - 1), end = '')
	
# Rest	      
	      
for i in range(len(p.coef) - 2, -1, -1):
	c = p.coef[i]
	if c < 0:
		print(' - {:}'.format(-int(c)), end = '')
	elif c > 0:
		print(' + {:}'.format(int(c)), end = '')
	if i >= 10:
		print(' x^{{{:}}}'.format(i), end = '')
	elif i > 1:
		print(' x^{:}'.format(i), end = '')
	elif i == 1:
		print(' x', end = '')
	else:
		print()
