#!/usr/bin/python3

import sys

def show_soln(i, j):
    if j - i >= 1:
        if j - i != len(n) - 2:
            print('(', end ='')
        mk = mink[i][j]
        show_soln(i, mk)
        print(' * ', end = '')
        show_soln(mk + 1, j)
        if  j - i != len(n) - 2:
            print(')', end ='')
    else:
        print(chr(ord('A') + i), end = '')

def show_Tk():
    for i in range(len(n) - 1):
        print(i + 1, end =': ')
        for j in range(len(n) - 1):
            print('{:3}, {:1}; '.format(T[i][j], mink[i][j] + 1), end = '')
        print()

fin = open(sys.argv[1])
n = [x for x in map(int, fin.readline().split())]
fin.close()

T = [([0] * (len(n) - 1)) for x in range(len(n) - 1)]
mink = [([0] * (len(n) - 1)) for x in range(len(n) - 1)]

for i in range(len(n) - 1):
    mink[i][i] = i

for d in range(1, len(n) - 1):
    for i in range(len(n) - d - 1):
        mt = 100000
        for k in range(i, min(i + d, len(n) - 1)):
            t = T[i][k] + T[k + 1][i + d] + n[i] * n[k + 1] * n[i + d + 1]
            if t < mt:
                mt = t; mk = k
        T[i][i + d] = mt; mink[i][i + d] = mk

show_soln(0, len(n) - 2)
print()
print()

show_Tk()
