#!/usr/bin/env python


import numpy
import scipy.interpolate
import matplotlib.pyplot as plt

def f(x):
    return 1 / (1 + 25 * x ** 2)

x = numpy.arange(-1, 1, 0.01)

for n in range(4, 12, 2):
    cp = [numpy.cos((2 * j + 1) / (2 * n + 2) * numpy.pi)
	    for j in range(n + 1)]
    ip = scipy.interpolate.BarycentricInterpolator(
	    cp,
	    [f(x) for x in cp])

    fig = plt.figure()
    plt.ylim(-1, 2)
    plt.plot(x, f(x), x, ip(x), 'r')
    fig.savefig('chebyshev-{}.pdf'.format(n))
